// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  Emoji: string
  EmojisWrapper: string
  EmojisWrapper__Emoji: string
  EmojisWrapper__EmojiSvg: string
  EmojisWrapper__Title: string
}
export const cssExports: CssExports
export default cssExports
